# Generated by Django 4.1.7 on 2023-03-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad", name="price", field=models.PositiveIntegerField(),
        ),
    ]
